# Generated by Django 5.0.6 on 2024-07-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbGameMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_match_id', models.IntegerField(null=True)),
                ('cl_started_at', models.DateTimeField(null=True)),
                ('cl_finished_at', models.DateTimeField(null=True)),
                ('cl_map', models.CharField(max_length=100, null=True)),
                ('cl_server', models.CharField(max_length=100, null=True)),
                ('cl_lobby_name', models.CharField(max_length=100, null=True)),
                ('cl_created_at', models.DateTimeField(null=True)),
                ('cl_update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TbGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_groupname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TbMatchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_match_id', models.IntegerField(null=True)),
                ('cl_team_id', models.IntegerField(null=True)),
                ('cl_aoe2_net_id', models.IntegerField(null=True)),
                ('cl_civ', models.CharField(max_length=100, null=True)),
                ('cl_match_result', models.IntegerField(null=True)),
                ('cl_created_at', models.DateTimeField(null=True)),
                ('cl_update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TbPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_aoe_version', models.CharField(max_length=100, null=True)),
                ('cl_player_name', models.CharField(max_length=100, null=True)),
                ('cl_avatar_url', models.CharField(max_length=200, null=True)),
                ('cl_player_alias', models.CharField(max_length=100, null=True)),
                ('cl_elo_unranked', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cl_elo_1vs1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cl_elo_team', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cl_drops', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cl_streak', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cl_last_win_count', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cl_last_lose_count', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cl_elo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cl_final_elo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TbMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_username', models.CharField(max_length=100, null=True)),
                ('cl_password', models.CharField(max_length=100, null=True)),
                ('fk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalApp.tbgroup')),
                ('fk_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalApp.tbplayer')),
            ],
        ),
    ]
