# Generated by Django 5.0.6 on 2024-07-27 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_log', models.CharField(max_length=100, null=True)),
                ('fk_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalApp.tbmember')),
            ],
        ),
    ]
